# A left prompt
format = """$all"""

# move time to the right
right_format = """$time"""

[jobs]
symbol = "+"
number_threshold = 4
symbol_threshold = 1

[character]
error_symbol = "[➜](bold #ff5555)"
success_symbol = "[➜](bold #50fa7b)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
show_always = true
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[time]
disabled = false
time_format = "%l:%M %p"
style = "bold #f1fa8c"
format = '[$time]($style)'
