format = """
$time\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#ffb86c"

[character]
success_symbol = "[](#bd93f9 )"
error_symbol = "[](#ff5555 )"
vimcmd_symbol = "[](#50fa7b )"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "#8be9fd"
conflicted = " "
untracked = " "
modified = " "
staged = " "
renamed = " "
deleted = " "
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#bd93f9"

[cmd_duration]
format = "[$duration]($style) "
style = "#f1fa8c"

[python]
format = "[$virtualenv]($style) "
style = "#44475a"

[time]
disabled = false
time_format = "%l:%M %p"
style = "#f1fa8c"
format = '[$time ]($style)'